sudo: false

language: php

php:
    - 8.0
    - 7.4
    - 7.3
    - 7.2

install:
    - make vendor/installed
    - travis_retry wget -O phive.phar https://phar.io/releases/phive.phar
    - travis_retry make tools/box tools/giroapp PHIVE_CMD="php phive.phar"

script:
    - make test PHIVE_CMD="php phive.phar"
