sudo: false

language: php

php:
    - 7.4
    - 7.3
    - 7.2

install:
    - make vendor/installed
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - make tools/box PHIVE_CMD="php phive.phar"

script:
    - make test
